name: My Test Workflow
on: push
jobs:
    first_test_job:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout Repo
           uses: actions/checkout@v4
         - name: Exection
           run: |
              echo "Multiple Line commands"
              cat README.md
              uname -m >> arch.txt
              ls -ltra

        #  - name: List files
        #    run: ls -ltra & pwd
        #  - name: Read Files
        #    run: cat README.md
